### ISSUE TITLE
Part of filtered data recording is missing

### ISSUE THREAD

**Issue by tang232** [open-ephys/analysis-tools#54]
Hi all,

I recently started to use a new openephys acquisition board, and I usually acquire raw data and filtered data for LFP and unit analysis. 
I recently noticed that the size of filter data is smaller than the raw data, and sometimes I got a few channels that have intact recordings, but sometimes none of the channels has intact recording, though I did not change the configuration file.

Here is my configuration: 
![image](https://user-images.githubusercontent.com/22801266/29005533-383bd214-7aab-11e7-9897-79e75737a7ab.png)

Does anyone have any idea what is wrong in my recording?

Many thanks!
Yu

**Comment by tang232** [comment]
It seems like when I record all of the channels, the recording is intact, but when only 64 channels are selected, part of the filtered data is missing

**Comment by jsiegle** [comment]
Can you try updating to the latest version of the GUI (0.4.2.1)? This sounds very similar to a bug we just fixed (https://github.com/open-ephys/plugin-GUI/issues/154).

**Comment by tang232** [comment]
Hi,

Thanks for the reply! I have the most updated version, but still have this problem. Right now, I'm saving all channels (1-128), and then deleting the empty channels (65-128), which gave me recordings of the full length.

Thank you,
Yu

**Comment by aacuevas** [comment]
Hi,

Which exact version were you using? Although we fixed the bug for 0.4.2.1 in the master branch and binary builds, the development branch code has been unfixed for a while after that, since we had to resolve some code merge conflicts. It should be already fixed on all versions of the code but it would be important to know if some version of this bug still remains.

Best,
Aarón

**Comment by tang232** [comment]
Hi Aaron,

Sorry for this late reply! I could not find this email for a long time
since I last opened it. So I downloaded the 64-bit zip file from
https://open-ephys.atlassian.net/wiki/spaces/OEW/pages/491621/Windows, but
I don't know exactly what version it is. (I wanted to start experiment as
soon as possible, but not good at building software by myself, so this way
seems the simplest way to install openephys)

I apologize again for this late reply! and Thank you for explanations!

Yu
2017-08-16 22:11 GMT-04:00 Aarón Cuevas López <notifications@github.com>:

**Comment by jsiegle** [comment]
Apologies—that's an outdated link.

Please use this one to get the latest version: https://github.com/open-ephys-GUI-binaries/open-ephys/archive/windows.zip

Hopefully that will solve the problem! I just updated the link on the wiki.

**Comment by tang232** [comment]
Thank you a lot!

Yu
